### ISSUE TITLE
i want to store the tagged data in my db ..from  where i can get tag generator ocde

### ISSUE THREAD

**Issue by geek-kumar** [timseverien/taggd#10]

**Comment by geek-kumar** [comment]
i want to store the tagged data in my db ..from  where i can get tag generator code

**Comment by timseverien** [comment]
You can access the data using `taggd.data`:

    var taggd = $('.taggd').taggd( options, data );
    console.log(taggd.data);

**Comment by geek-kumar** [comment]
thnkx ....
one more ques is there that if i creates a tag  and left it blank but if i try to create another tag then the blank tag should be deleted and can i do it  please answer and thankx in advance

**Comment by timseverien** [comment]
Try this:

    var options = {
          handlers: {
            change: function() {
              taggd.setData(taggd.data.filter(function(entry) {
                return typeof entry.text === 'string' && entry.text > 0;
              }));
            }
          }
        },
        taggd = $('.taggd').taggd( options, data );

**Comment by geek-kumar** [comment]
this is my code which i ma trying to use to delete the tag but when the current empty tag is deleted  and then when i create a new  tag the deleted tag also comes  how can i delete it permanently


				$(document).on('click','.taggd-wrapper',function(){
					
					
					
					$("input.tagsInput").focusout(function(){
						
						
						if(!$(this).val())
						  {
							  
							  
							  
							  var ok=confirm ('Are you sure you want to delete this tag');
							  if(ok){
								  	var _this = this;
									var $e = $(this);
								  this.data = data;
								   $(this).parent().prev().remove();
								   $(this).parent().remove();
								   
								   //	var options = {
      
			
			
			
								   
								   
									console.log(data); 
									  
									 
								  
								  
								  
								  
								  
								  }  

						  }
						
						
						
						});
					
					
					
					
					})

**Comment by timseverien** [comment]
Try this: http://jsbin.com/bayagayipe/1/edit?js,output

**Comment by geek-kumar** [comment]
hey thnkx it worked perfectly

**Comment by geek-kumar** [comment]
hey dear i am trying to use this plugin with  nivo-lightbox  v1.2 but its not working in light box .when the image open in light box  marker stop working.please help to solve this problem.How can it work with light box

**Comment by timseverien** [comment]
Hey @geek-kumar. Could you please create a new issue for this? It’s easier to track (and not forget) issues :)
