### ISSUE TITLE
using image tag in nivo-lightbox

### ISSUE THREAD

**Issue by geek-kumar** [timseverien/taggd#11]
hey dear i am trying to use this plugin with nivo-lightbox v1.2 but its not working in light box .when the image open in light box marker stop working.please help to solve this problem.How can it work with light box.and why its not working with lightbox  even anyother image tag plugin is not working with lightbox

**Comment by timseverien** [comment]
Similar to #15, I suspect it’s because lightboxes are hidden on default, therefor preventing taggd from initialising properly. Like #15, there’s no fancy way to fix that. There are only hack arounds.
