### ISSUE TITLE
Request / Question: Printing tags?

### ISSUE THREAD

**Issue by joshuapinter** [timseverien/taggd#14]
Great library, Tim! Beautiful and clean.

I'm interested in printing the tags when I print the image, but I don't see the tags when just printing the page. Any ideas on how to handle this properly?

Thanks.

**Comment by pisdoktor** [comment]
same question for me too.

**Comment by timseverien** [comment]
Sorry for the late reply. Can either of you set up a demo for me to test, please?

**Comment by joshuapinter** [comment]
We ended up having to use [jCanvas](http://calebevans.me/projects/jcanvas/) as our "tagging" requirements became more complex so I don't have anything readily available.

Maybe @pisdoktor does, though.

**Comment by pisdoktor** [comment]
i am working another project now. I will set up a demo for u soon @timseverien
