### ISSUE TITLE
Wont load within tab

### ISSUE THREAD

**Issue by nsweeting** [timseverien/taggd#15]
Hi there,

I feel as though this is probably a simple thing to fix...I'm just fairly new to javascript/jquery, etc.

I have an html page with some tabs:

```html
	<div class="tabs">
		<ul class="nav nav-tabs nav-justified">
			<li class="active">
				<a href="#basicinfo" data-toggle="tab"><i class="fa fa-lg fa-user"></i>&nbsp;&nbsp;Basic Info</a>
			</li>
			<li>
				<a href="#slipinfo" data-toggle="tab"><i class="fa fa-lg fa-anchor"></i>&nbsp;&nbsp;Slip Info</a>
			</li>	
		</ul>
		<div class="tab-content">
			<%= render 'basicinfo' %>
			<%= render 'slipinfo' %>
		</div>
	</div>
```

Rails will render my partial 'slipinfo' containing my taggd image. HTML below.

```html
<div id="slipinfo" class="tab-pane">
  <h4 class="mb-xlg">Slip Info - <%= @dock_area.name %></h4>
  <br>
  <center><%= image_tag(@dock_area.picture.url, alt: 'dock_image', class: 'taggd rounded img-responsive') %></center>
  <br>
</div>
```

And of course, I have my javascript (well...coffeescript) to load taggd - I'm just using this from an example.

```coffeescript
options = 
align: y: 'top'
offset: top: 15
handlers: click: 'toggle'
edit: true
data = [
  {
    x: 0.62
    y: 0.7
    text: 'Rope'
  }
  {
    x: 0.51
    y: 0.5
    text: 'Bird'
  }
  {
    x: 0.40
    y: 0.3
    text: 'Water, obviously'
  }
]
taggd = $('.taggd').taggd(options, data)
```
No tags appear on the image though. If I take the image tag out of the tab, everything works as normal. Any help? 

Thanks

**Comment by timseverien** [comment]
Hey @nsweeting. You will find that many jQuery plugins, or at least the ones that try to determine the dimensions of an element, will not work within tabs. On default, Bootstrap hides tab panes, keeping the nested elements from rendering, making it impossible for jQuery to get the dimensions.

Unfortunately, there’s nothing I can do here. You can try to force the tab panes to be visible until, and hide them again at `window.load`.
