### ISSUE TITLE
Handler events not fired

### ISSUE THREAD

**Issue by mothman1** [timseverien/taggd#18]
I have the following options but handler event is never triggered. - I expected the event to fire when I click on the image that I'm tagging.

Any advise?

var options = {
						edit: true,
						
						// Aligning the text popups
						align: {
							y: 'top'
						},
						// The (relative) offset of the popups in pixels
						offset: {
							top: 15
						},

						// event handlers of the tags
						handlers: {
							// Any vanilla JavaScript event is a valid key
							//click: 'toggle'
							click: function(e) {
						      alert('You clicked the image');

						      this; // the DOM Node
						      e;    // the Event
						    }
						}
					};

**Comment by timseverien** [comment]
That is odd. Not sure what to do with this, either. Taggd 2 is under construction, so if this turns out to be a bug, v2 should solve this.
