### ISSUE TITLE
is it possible to tag the image with the "arrow" sign instead of the circle dot?

### ISSUE THREAD

**Issue by josietam** [timseverien/taggd#19]
Thanks for your great work on building this library.  We are using it already!

If we would like to replace the tagging action by adding an arrow and the arrow points to the circle dot, how can we make it happen?

Thank you!

**Comment by timseverien** [comment]
I haven’t received notification of past few issues—I’m so sorry.

Even though I’m probably way too late, you can style the mark using CSS. It’s just a regular span with the `taggd-item`-class. If you set a height, width, and background-image, you can use an image instead of the dot.

**Comment by josietam** [comment]
Hi Tim,

http://jsfiddle.net/URWru/ <http://jsfiddle.net/URWru/>

Thanks for replying me.  What we would like to do is to include the drawing line (as in the JS Fiddle) to the taggd library.  However, since both your library n the this one manipulate the DOM by ‘mouse click’, i wonder if any hints you can share with me about your library that i can 
1) either combining the two actions together with 1 click (ie. when a user clicks on an image, a line is drawn.  When a user releases their mouse, it triggers the taggd)

2) Or, user can choose to draw lines & make taggd

Thanks a lot!  
Josie

**Comment by timseverien** [comment]
Hey Josie,

This is what you want, right?
http://jsfiddle.net/URWru/1134/

**Comment by josietam** [comment]
Hi Tim,

That's awesome!  Yes it is what I wanted.  And what you have done is really amazing :)  Thank you a lot!

Josie

**Comment by timseverien** [comment]
Happy to help!
