### ISSUE TITLE
Feature: while in edit mode, click and drag tag.

### ISSUE THREAD

**Issue by Jeradin** [timseverien/taggd#20]
Great plugin, just started playing around with it. I was wondering if there was any plans to add an option to drag/move taggd markers when in edit mode?

Thanks!

**Comment by timseverien** [comment]
Due to technical limitations, I choose not to. However, I plan to release Taggd 2 soon, that will work better and include improvements for editing. That also means this project will be discontinued. Would you like to receive a comment when Taggd 2 is released?

**Comment by Jeradin** [comment]
Thanks Tim, I would be very interested in receiving a comment when Taggd 2 is released.

Cheers!

**Comment by abitdodgy** [comment]
@timseverien does v3 support drag functionality? How much work does it involve?

**Comment by timseverien** [comment]
@abitdodgy Nope. It shouldn't be that hard, as Taggd has pretty sweet pub/sub now, making it easy to update things, but it would make the library a bit clunky. You could implement it perfectly with user-code:

```js
const addDragDrop = (tag) => {
  // Add drag-n-drop functionality on tag.buttonElement
  tag.buttonElement.addEventListener('drag', () => {
    // Determine new X and Y position
    // const newPositionX = ?
    // const newPositionY = ?

    tag.setPosition(newPositionX, newPositionY);
  });
};

// Add drag-n-drop functionality for existing tags
taggd.getTags().forEach(addDragDrop);
// Add drag-n-drop functionality for new tags
taggd.on('taggd.tag.added', (taggd, tag) => addDragDrop(tag));
```

**Comment by abitdodgy** [comment]
@timseverien thanks. Are there any built in functions to get the position in the public API. I had a look and saw [getPositionStyle](https://github.com/timseverien/taggd/blob/master/src/scripts/classes/Tag.js#L336).

Would that do it? So building on your example:

```javascript
const addDragDrop = (tag) => {
  // Add drag-n-drop functionality on tag.buttonElement
  tag.buttonElement.addEventListener('drag', () => {
    // Determine new X and Y position
    // const newPositionX = tag.getPositionStyle().left
    // const newPositionY = tag.getPositionStyle().left

    tag.setPosition(newPositionX, newPositionY);
  });
};
```

**Comment by timseverien** [comment]
I'm not too familiar how drag and Drop API works, but I think the `drag` event calls the handler with an event that holds information where the cursor is. You then have to convert the mouse coordinates to image coordinates of a 0-1 range. Consider this pseudo-code:

```js
element.addEventListener('drag', (e) => {
  const mouseX = e.mouseXRelativeToContainer;
  const mouseY = e.mouseYRelativeToContainer;

  const newPositionX = mouseX / imageWidth;
  const newPositionY = mouseY / imageHeight;

  tag.setPosition(newPositionX, newPositionY);
});
```
