### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by jAgnaldoGomes** [timseverien/taggd#21]
Seria bem esclarecedor se tivesse um exemplo de disparo de evento.
Fiz algumas alterações no seu exemplo e só exibe as informações de uma tag que é criada junto com o controle, Se eu adicionar uma tag os eventos param de serem disparados.
Preciso capturar os eventos na minha página para controlar o conteúdo do plugin.
Será que pode me ajudar?

It would be clearer if it had an event trigger example.
I made some changes in your example and only displays the information in a tag that is created with the control, If I add a tag to stop events from being fired.
I need to capture the events on my page to control the content of the plugin.
Can you help me?

**Comment by timseverien** [comment]
Wow, I wasn’t notified of this issue. My sincere apologies. Can you show an example?
