### ISSUE TITLE
Resizing with JQuery

### ISSUE THREAD

**Issue by ProbadorGit** [timseverien/taggd#22]
I am holding my image in a structure like this:

```
<li>
    <figure>
        <img ...> 
    </figure>
</li>
```
I apply taggd to the image:
`$('img').taggd(options, data);`
Then I need to resize the image by using an <input> so I set:
```
$('li').css('height', newSize +'px');
$('img').css('max-height', newSize +'px');
```

However the tagged-items are not resized (they stay under the `<div class="taggd-wrapper">`). Is there a proper way to do this or should I also mess with taggd created elements?

Note: I am defining data coordinates in terms of [0-1]

**Comment by timseverien** [comment]
You could try the `updateDOM()` method:

```js
var taggd = $('.my-element').taggd(options, data);
taggd.updateDOM();
```

**Comment by ProbadorGit** [comment]
Thanks. In the end I used windows resize instead. However, I found an issue when a CSS transition is used (https://fiddle.jshell.net/3w7zvwzg/). It doesn't resize unless you manually move the container window.

**Comment by timseverien** [comment]
Ah, tough one. For now, you could trigger another resize once the animation is done:

```js
const $window = $(window);

$window.on('transitionEnd', function () {
    $window.trigger('resize');
});
```

**Comment by ProbadorGit** [comment]
Ok, thanks. I will try and otherwise I will leave out the transition. I heard you will release a v2, is that correct? Any timing estimation?

**Comment by timseverien** [comment]
Correct! I expect it to be this or next week :)

**Comment by ProbadorGit** [comment]
Great. I will try it!
