### ISSUE TITLE
Firing when user add/remove tags

### ISSUE THREAD

**Issue by salvatorecapolupo** [timseverien/taggd#23]
Hi,

what about firing events i.e adding / removing a tag?

For example, I would expect:

$( "button" ).on( "add_tag", alert("happy, you just added a tag") )
$( "button" ).on( "remove_tag", alert("sad, you just removed a tag") );

For the sake of clarity, my request would be expressed also like: how to fire clicks on √ (submit) e X (close) elements in text boxes?

**Comment by timseverien** [comment]
Hey,

For now, I only have the `change` event handler. There is a Taggd 3 in the making, which definitely will include explicit events, but I’m unsure when it will be published due to personal issues.
