### ISSUE TITLE
Taggd with React?

### ISSUE THREAD

**Issue by dylanfpaul** [timseverien/taggd#24]
Is taggd unusable with React? I see the <span> elements that taggd produces but they are all 0x0 dimension. I am linking the css and the library properly. Also, the image I am trying to render the tags to is being resized because the taggd-wrapper is messing with it. I am basically trying to implement taggd on an image that is within a modal in React and none of it is working even though the library is being accessed and the taggd elements are being created.

**Comment by timseverien** [comment]
I don’t know. I never used React. Is any jQuery library React-compatible?

Either way, 3.0 is near completion and doesn’t require jQuery. Perhaps it will work better for you. It’s on the #3.0 branch.

https://github.com/timseverien/taggd/tree/3.0?
