### ISSUE TITLE
Tags with different colors

### ISSUE THREAD

**Issue by Aliuken** [timseverien/taggd#25]
Could you let to put the tags in different colors? For example, one color for people and another different for concepts, instead of eveything pink.

**Comment by timseverien** [comment]
I would recommend keeping style in CSS, leaving you with these two options:

1. Use CSS `:nth-child` pseudo-selector: `.something:nth-child(2) { color: #f00; }`
2. Use [custom attributes|https://github.com/timseverien/taggd#3-what-is-data-and-how-do-i-get-it] in conjure with CSS. In the data array, you can set a custom attribute, like a class, and style that with CSS.
