### ISSUE TITLE
Trouble in implementing v3.0.1

### ISSUE THREAD

**Issue by prtkkmrsngh** [timseverien/taggd#27]
Any example please?

**Comment by timseverien** [comment]
For now you can look at the manual tests:

- https://github.com/timseverien/taggd/blob/master/tests/manual/basic.html
- https://github.com/timseverien/taggd/blob/master/tests/manual/editor.html

I’ll try to add some proper examples to the documentation as soon as possible :)

**Comment by prtkkmrsngh** [comment]
Thanks :-)
