### ISSUE TITLE
Bug in deleteTags() function! Tags will never be deleted

### ISSUE THREAD

**Issue by prtkkmrsngh** [timseverien/taggd#37]
Bug in deleteTags function as no tag is being deleted. Have a look at your(@timseverien) code here
[https://github.com/timseverien/taggd/blob/master/dist/taggd.js#L2187](https://github.com/timseverien/taggd/blob/master/dist/taggd.js#L2187)

.slice does not mutate the array, you could use .splice()

Replacing slice with splice worked for me!

**Comment by timseverien** [comment]
Thanks for the report dude :)
