### ISSUE TITLE
Save the positions ?

### ISSUE THREAD

**Issue by paulvasseur** [timseverien/taggd#44]
Hi, 
how can i save positions for storage in a database ?

Thx

**Comment by timseverien** [comment]
You can use the `taggd.tag.add` event to perform an action whenever a new tag is added. With the [`Taggd.getTags()`](https://doclets.io/timseverien/taggd/v3.0.8#dl-Taggd-getTags) method you can get all tags currently stored in that instance.

```js
const taggd = new Taggd(image, options, data);
taggd.enableEditorMode();

taggd.on('taggd.tag.add', () => {
  const tags = taggd.getTags();

  // Send POST request to server with the tags
  const req = new XMLHttpRequest();
  req.open('POST', 'api/update-tags', true);
  req.send(JSON.stringify(tags));
});
```
