### ISSUE TITLE
Identify each Tag

### ISSUE THREAD

**Issue by paulvasseur** [timseverien/taggd#47]
Hi,

Is it possible to add an id or a class on the button element ?

Thx

**Comment by timseverien** [comment]
Yep, you can! You can define [Tag](https://doclets.io/timseverien/taggd/master#dl-Tag)s with attributes:

```js
new Taggd.Tag(position, text, {
  id: 'foo',
  class: 'bar',
});
```

Or, if you’re using `Taggd.Tag.createFromObject`:

```js
Taggd.Tag.createFromObject({
  position: ...,
  text: ...,
  buttonAttributes: {
    id: 'foo',
    class: 'bar',
  },
});
```
