### ISSUE TITLE
It doesn`t work on Firefox

### ISSUE THREAD

**Issue by rbernardezitteria** [timseverien/taggd#48]
You can not edit tags in Firefox :( . Is there any solution?

**Comment by timseverien** [comment]
What isn’t working _exactly_? Please elaborate.

**Comment by rbernardezitteria** [comment]
If you use the generator and you upload a photo with Firefox, you can create a new tag but you cant edit the text. Yesterday I was using your library and I discovered a bug. When you create a new tag you insert buttons into a button (image) and it fails in Firefox.
![image](https://cloud.githubusercontent.com/assets/23172482/19999248/7c011486-a271-11e6-9e62-fa32e7e8e1a6.png)

**Comment by timseverien** [comment]
I’m suspecting this is a duplicate of #43. Do the tooltips disappear after clicking a tag?

**Comment by alexandru-coman** [comment]
The problems on Firefox and Safari is that you cannot select anything from the popup (inputs, buttons), even with the fix from #43.

**Comment by timseverien** [comment]
I thought updating the generator would fix it, but it didn't. Reopening for further investigation.

**Comment by timseverien** [comment]
Should be fixed by #49 🎉 
Please update to [3.1.1](https://github.com/timseverien/taggd/releases/tag/v3.1.1).
