### ISSUE TITLE
Close Taggd popup on save

### ISSUE THREAD

**Issue by robiningelbrecht** [timseverien/taggd#56]
Hi,

Is it possible to close the popup when the "save" button is clicked? 
I'm using this to bind tag changed event, but I can't seem to figure out how to close the popup.

`taggd.on('taggd.tag.changed', myCallback);`

**Comment by timseverien** [comment]
Yeah, you can! You can use `tag.hide()`. For events that are registered on the `taggd` instance, `tag` is the second parameter. See https://doclets.io/timseverien/taggd/master/events#taggd-events.

```js
taggd.on('taggd.tag.changed', function onTagChange(taggd, tag) {
  tag.hide();
});
```
