### ISSUE TITLE
Images without "width:100%" are broken

### ISSUE THREAD

**Issue by robiningelbrecht** [timseverien/taggd#57]
In my application I use different kind of image styles, but the taggd css file puts a width of 100% on all my taggd images which makes my image styles useless bacause they have the width of their parent container...

When I override this line of css with 

`img.taggd__image{
  width: inherit;
}`

the taggd library seems to flip out when I apply this css. Why do the images have to have a width of 100%?

**Comment by robiningelbrecht** [comment]
I have a temporary fix for this issue: I wrapped my taggd images in a div and with JS I set the dimensions of the div equal to the image dimensions.

This way my images styles are respected and the "width: 100%" can be applied.

**Comment by timseverien** [comment]
I'll have a look if I can mention this in the docs, but I wish to keep it this way. The positioning of the tags is in percent, making it robust and correct now matter how the image scales. I cannot make style assumptions for the containing element, either. So yeah, wrapping the image in an element is the best "fix".

**Comment by timseverien** [comment]
Clarified via docs. See 9ccbb3ebad4cbd48e18bad46786ed112e08665d1
