### ISSUE TITLE
[Question] Pop-up functionality

### ISSUE THREAD

**Issue by abitdodgy** [timseverien/taggd#60]
I'm evaluating the plugin to see if it fits my use case. I want to show a form component in a different location once a tag is added. For example:

1. User clicks image
2. Circle appears on image to indicate tag was placed (no popup)
3. In another location, a fieldset is inserted into an existing form and is fed the tag coordinates

I need to feed the form several things other than coordinates. Is it possible to disable the popup and add a function to handle the fieldset insertion? Something like...

```javascript
const addfieldSet = (tag) => {
  // Logic to add fieldset here
  // The `tag` arg is used to provide coordinates 
}
taggd.on('taggd.tag.add', (taggd, tag) => addfieldSet(tag));
```
I have to repeat write something similar for each event (deleting, dragging, reordering, etc...)... so it might get complicated quickly. But am I on the right track with my thinking?

Maybe I can use the popup in some way and augment it instead?

**Comment by timseverien** [comment]
Sounds doable. I would just not show the popup, and use the tags as coordinates. In addition to your code, you could do:

```js
// Never show tags
taggd.on('taggd.tag.show', () => false);
```

Although it’s possible, I’m wonder whether you should. A lot of taggd’s functionality is ignored or disabled, but still present in the bundle. You’re free to copy bits and pieces from the source code.

I recon you’re particularly interested how tags are created:

```js
const getElementOffset = require('offset');
const getScrollTop = require('scrolltop');

// The wrapper of `image` and the to be added tags
const wrapper = ...;
// The clickable image
const image = ...;

image.addEventListener('click', (e) => {
  const scrollTop = getScrollTop();
  const offset = getElementOffset(this.image);
  const position = {
    x: (e.pageX - offset.left) / image.width,
    y: (e.pageY - offset.top - scrollTop) / image.height,
  };

  addTag(wrapper, position);
});
```

Based on: https://github.com/timseverien/taggd/blob/master/src/scripts/classes/Taggd.js#L36

And how they are shown:

```js
// https://github.com/timseverien/taggd/blob/master/src/scripts/classes/Tag.js#L336
const getPositionStyle = (x, y) => {
  return {
    left: `${x * 100}%`,
    top: `${y * 100}%`,
  };
};

const addTag = (wrapper, position) => {
  const tag = document.createElement('div');
  const { left, top } = getPositionStyle(position.x, position.y);
  
  // https://github.com/timseverien/taggd/blob/master/src/styles/taggd.css#L31
  tag.className = 'tag';
  tag.style.left = left;
  tag.style.top = top;

  wrapper.appendChild(tag);
};
```

Where `parentElement` should be a lot like [`.taggd__wrapper`](https://github.com/timseverien/taggd/blob/master/src/styles/taggd.css#L12).

**Comment by abitdodgy** [comment]
@timseverien  OK, from what I understand, you think it's better to roll my own using some components from taggd? Probably this is the best solution. Thanks for the help!
