### ISSUE TITLE
JQuery Port

### ISSUE THREAD

**Issue by Alexa69** [timseverien/taggd#61]
Hi
Your code works just fine, do you have any plan to port it to JQuery ? 

Thank you

**Comment by timseverien** [comment]
No. Taggd used to have jQuery as dependency, but I deliberately got rid of it.

Although the API will feel less familiar, you can still use it with jQuery, though:

```js
const $myImage = $('img.my-image');
const taggd = new Taggd($myImage.get(0));
```
