### ISSUE TITLE
I want to add form and get data 

### ISSUE THREAD

**Issue by nitinjiniguru** [timseverien/taggd#62]
As i have requirement for the open poupup on click of the button and open form and on submit button retrieve data.

Is it possible in our library?

as i have added static Html but not able to retrieve the data

**Comment by timseverien** [comment]
Do you want to put the entire form in the popup?

```js
const myForm = document.querySelector('.my-form');

// Show form when any tag is opened
taggd.on('taggd.shown', () => {
  // show form
  myForm.classList.remove('is-hidden');
});

// Fetch data when myForm is being submitted
myForm.addEventListener('submit', (e) => {
  console.log(taggd.getTags());
});
```

**Comment by nitinjiniguru** [comment]
yes i want to put entire form in the popup and where to set all fields inside the library?

**Comment by timseverien** [comment]
Well, you _can_ put HTML in a tag, by setting the `text` property.

```js
const image = document.getElementById('my-image');
const options = {};
const tags = [
  Taggd.createFromObject({
    text: '<form>...</form>', // <= HTML goes here
  })
];

const taggd = new Taggd(image, options, tags);
```

But just because you _can_ doesn't mean you _should_. Give some thought whether Taggd isn't bloated for your purpose. If you decide not to use Taggd, you're free to copy bits and pieces from the library.
