### ISSUE TITLE
Cover-fit image tagging

### ISSUE THREAD

**Issue by wevaio** [timseverien/taggd#64]
Hey Tim,

I have a slideshow with images as follows:

```
img {
   width:100vw;
   height:100vh;
   object-fit:cover; 
}
```

This makes the images fullscreen and behave like `background-size:cover;`, so they fill out the whole viewport on any screen size without distortion. I would like to tag certain points on these images, but in my case the `object-fit:cover;` property makes the tagged positions inaccurate. I have tried everything from CSS hacks to improving your code, but I am out of ideas. Do you have any solution or workaround?

I've posted my question on S/O as well, you can find it [here](https://stackoverflow.com/questions/45125926/responsive-cover-fit-image-tagging). Only one answer so far, beginning with "Is not possible." :(

**Comment by timseverien** [comment]
I think the "is not possible" refers to your wish to scale without distortion.

Anyway, read [the note on image styles](https://github.com/timseverien/taggd#note-on-image-styles).

You will probably want to add the following to your CSS:

```css
.taggd {
  height: 100vh;
  width: 100vw;
}

.taggd__image {
   display: block;
   height: 100vh;
   width: 100vw;
   object-fit: cover; 
}
```

The first CSS block will set the `.taggd` container to a 100% width and height. The second block sets the image style using the class that Taggd adds to the image. This is preferred over the `img` selector, as [a class selector is more specific than a tag selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#Selector_Types).

**Comment by wevaio** [comment]
Thanks for the quick reply!

It seems that I am not able to get it working. :( 
Would you mind taking a look at it?
What am I missing?

Example: [https://weva.io/test/](https://weva.io/test/)

**Comment by timseverien** [comment]
Works for me on Chrome and Firefox.

Only now I notice that your use-case might have some down-sides you will want to consider.

Each tag is positioned based on it's container. In your use-case, the image often overflows the container, causing the tag positions to be incorrect in respect to the image. I suppose this can be solved by setting `object-fit: cover` to the container, and set the image width and height to `100%`. I think that will make the tags scale with the image.

A drawback of above fix is that some tags will overflow on different aspect ratios. Although testable for a wide range of devices, I can resize my browser into any aspect ratio, making it very hard to make sure all tags are always visible.

**Comment by wevaio** [comment]
I guess I messed up phrasing my question, let me give it another try :D

What I am trying to achieve is that even if my taggd images have an `object-fit:cover` CSS property assigned to them, the tags must stay in position when the window crops and/or resizes the image. 

Taggd perfectly handles cases when the width and height of the image scales proportionally, but in my case, I would like to have images that fill the whole browser window (regardless of the window size). This can only be done by using `object-fit:cover`, but this way the positions of the tags can be incorrect in respect to the image – depending on the ratio.

As you mentioned, `object-fit:cover` can cause the images to overflow, and if the tagged part of the image overflows, the tags for that certain part won't be visible. That can only happen if the tags stay in their tagged positions all the time (even on cropping) – which is what I would like to accomplish.

I updated the test site above by setting `object-fit: cover` to the container and setting the image width and height to 100%, but this causes my image to scale proportionally, which means that it will not fit the window width and height (not like when the width and height are set to 100vw/100vh).

Any other ideas? :/

**Comment by timseverien** [comment]
Apparently, [`object-fit`](https://www.w3.org/TR/css3-images/#the-object-fit) only applies to [replaced element](https://www.w3.org/TR/CSS21/conform.html#replaced-element)s, like `<img>` and `<video>`. The style doesn't work on other elements.

That leaves us with a few options:

1. Ditch `object-fit` altogether and scale proportionally
2. Use JavaScript to simulate `object-fit` on the container 😦 
3. Calculate the image position and size, and move tags accordingly (which is hard, possibly inaccurate and probably very slow, so I discourage doing this)

**Comment by wevaio** [comment]
Thank you for being so kind and looking this matter – I might have found a solution to my problem, but I need to modify your code so the tagging starts from `center center` not `top left`. Can you help me in that? Where shall I look? I'm using v3.1.1.

**Comment by wevaio** [comment]
I managed to solve it by setting the images width and height according to the window width and height (scaling them proportionally). The images overflow to the sides when needed – which makes them behave like an `object-fit:cover` image, without losing the tags accuracy. Thanks for the help!

PS.: I'm placing links on the popup bubbles by putting `<a>` tags in the `text` strings, but if I'm viewing on mobile (tried it with iPhone 5s and iPad 2) I have to click twice on the bubble for the link to work. Any ideas on that?

**Comment by timseverien** [comment]
Hmmm. Not sure. Can you share some code?

**Comment by wevaio** [comment]
Sure! Here it is: 
https://weva.io/test20170725/

Thanks!

**Comment by timseverien** [comment]
I see the test page has been taken offline, and I haven’t been able to reproduce the issue. Have you managed to get it working?

**Comment by wevaio** [comment]
Tim,
thanks for getting back to me! I was thinking that you might have something else to do and have very little time to deal with this problem. Sorry for not giving you a heads up when deleting the test page!

Yes, I finally managed to get it working, but however, I decided to drop the bubbles with the captions and just go with the buttons. I've modified your `Tag()` function (see below) to create an `a` element for the button, and add a `link` string as `href`. Please keep in mind that this is more like a hack than a sophisticated solution for this awesome plugin of yours.

```
function Tag(position, text, link) {
    var buttonAttributes = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : {};
    var popupAttributes = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : {};
    (0, _classCallCheck3.default)(this, Tag);

    if (!ObjectIs.ofType(position, 'object') || Array.isArray(position)) {
      throw new TypeError(TypeErrorMessage.getObjectMessage(position));
    } else if (!('x' in position) || !('y' in position)) {
      throw new Error(position + ' should have x and y property');
    }

    var _this = (0, _possibleConstructorReturn3.default)(this, (Tag.__proto__ || (0, _getPrototypeOf2.default)(Tag)).call(this));

    _this.wrapperElement = document.createElement('div');
    _this.wrapperElement.classList.add('taggd__wrapper');

    _this.buttonElement = document.createElement('a');
    _this.buttonElement.classList.add('taggd__button');
    _this.buttonElement.target = "_blank";
    _this.buttonElement.href = link;

    _this.popupElement = document.createElement('span');
    _this.popupElement.classList.add('taggd__popup');

    _this.wrapperElement.appendChild(_this.buttonElement);
    _this.wrapperElement.appendChild(_this.popupElement);

    _this.isControlsEnabled = false;
    _this.inputLabelElement = undefined;
    _this.buttonSaveElement = undefined;
    _this.buttonDeleteElement = undefined;

    _this.buttonSaveElementClickHandler = function () {
      return _this.setText(_this.inputLabelElement.value);
    };
    _this.buttonDeleteElementClickHandler = function () {
      _this.emit('taggd.tag.delete', _this);
    };

    _this.text = undefined;

    _this.setButtonAttributes(buttonAttributes);
    _this.setPopupAttributes(popupAttributes);
    _this.setPosition(position.x, position.y);
    _this.setText(text);

	if(link == "#") {
      _this.buttonElement.style.display = "none";
	}

    _this.hide();
    return _this;
  }
```

I was surprised that placing links on the buttons/bubbles was not a default feature for Taggd, what's the reason for this? I would suggest adding such option in the further versions.

Thanks for your help!

**Comment by timseverien** [comment]
Oh, I never needed it, and taggd has taken enough time from me as it is ;)

I’m hoping someone is willing to take over the repo, actually.

**Comment by githubanonym** [comment]
hello,
i actually wanted to do the same thing. 
here is what i've done.
 maybe it will help someone in the future. 
if someone take over the repo, it would be great if this feature could be integrated in taggd.

```
function buildTags()
{

    // be aware that image.clientWidth and image.clientHeight are available when image is loaded
    var croppedWidth = false;
    var expectedWidth = 0;
    var croppedWidthHalf = 0;
    var imageWidth = 0;
    var croppedHeight = false;
    var expectedHeight = 0;
    var croppedHeightHalf = 0;
    var imageHeight = 0;
    var naturalRatio = image.naturalWidth/image.naturalHeight;
    var coverRatio = image.clientWidth/image.clientHeight;
    if(Math.abs(naturalRatio - coverRatio) < 0.01)
    {
        // the image is not cropped, nothing to do
    }
    else
    {
        if(naturalRatio > coverRatio)
        {
            // width is cropped
            croppedWidth = true;
            expectedWidth = image.clientHeight * naturalRatio;
            croppedWidthHalf = (expectedWidth - image.clientWidth)/2;
            imageWidth = image.clientWidth;
        }
        else
        {
            // height is cropped
            croppedHeight = true;
            expectedHeight = image.clientWidth / naturalRatio;
            croppedHeightHalf = (expectedHeight - image.clientHeight)/2;
            imageHeight = image.clientHeight;

        }
    }
    function calcy(y)
    {
        if(croppedHeight)
        {
            var positiony = y * expectedHeight;
            if(positiony >  croppedHeightHalf)
                return (positiony - croppedHeightHalf)/imageHeight;
            else // tag is outside the picture because cropped
                return 0; // TODO : handle that case nicely
        }
        else
            return y;
    }

    function calcx(x)
    {
        if(croppedWidth)
        {
            var positionx = x * expectedWidth;
            if(positionx > croppedWidthHalf)
                return (positionx - croppedWidthHalf)/imageWidth;
            else // tag is outside the picture because cropped
                return 0; // TODO : handle that case nicely
        }
        else
            return x;
    }

    var tags = [

      Taggd.Tag.createFromObject({
        position: { x: calcx(0.74), y: calcy(0.56) },
        text: 'some tag',
      }),
      Taggd.Tag.createFromObject({
        position: { x: calcx(0.9), y: calcy(0.29) },
        text: 'some other tag',
      }),

      ....
    ];
    var taggd = new Taggd(image, options, tags);

}
$(window).bind("load", function() {buildTags();});

```
