### ISSUE TITLE
Tags accept HTML

### ISSUE THREAD

**Issue by Miralo** [timseverien/taggd#65]
It could be nice if the Tag class can handle some HTML in addition of the simple "text" attribute.
For example: I want to use this awesome plugin in my ecommerce, and link some other products tagging them on the main image of one product. (sorry for may bad english).

What do you think?

**Comment by timseverien** [comment]
[It actually does](https://github.com/timseverien/taggd/blob/master/src/scripts/classes/Tag.js#L142) :)

**Comment by Miralo** [comment]
Oh, didn't noticed! Sorry!

**Comment by timseverien** [comment]
Probably because I didn't document it well ;)
