### ISSUE TITLE
The event "taggd.tag.delete" is called twice

### ISSUE THREAD

**Issue by anjey58** [timseverien/taggd#66]
I had a problem in emit taggd.tag.delete

Fixed so:
Step 1: i.buttonDeleteElementClickHandler=function(){i.emit("taggd.tag.delete2",i)},
Step 2: e.once("taggd.tag.delete2",function(){var r=t.tags.indexOf(e);r>=0&&t.deleteTag(r)}),

In my project:
taggd.on('taggd.tag.delete2', function (eltaggd, eltag) {
    console.log(eltag);
    console.log($(eltag.wrapperElement).index());
    // -----
    var tag=eltag.toJSON();
    console.log(tag);
    console.log(tag.position.x);
    console.log(tag.position.y);
    console.log(tag.text);
});

**Comment by timseverien** [comment]
Could you send me test code? The event is only called once in the tests.
